#!/bin/bash
# info system

################# CONSTANCE #######################
Title="Info sur kali"
jj="$(date +"%x %r %z")"
mj="mise à jour $jj   sur $USER"

################# Fonctions ######################
info_User()
{
	echo "information d'utilisateur"
	uname -a
}

info_disk()
{
	echo "information du system"
	lsblk
}

info_chemin()
{
	echo "information sur l'environnement$PATH"
	
}
info_show_time(){
	echo "Information sur la mise à jour "
	uptime
}
################### MAIN  ########################
cat <<_EOF_
<html>
 <head>
 <title>$Title </title>
 </head>$HOSTNAME
<body>
<h1>$Title</h1> 
<P>$mj</p>

<p>$(info_User)</p>
$(info_disk)
$(info_chemin)
$(info_show_time)  

</body>
</html>
_EOF_
